# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Maven Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11' # Choose the Java version you want

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build with Maven
      run: mvn clean package -B

    - name: Build Docker Image
      run: docker build -t ngv03/docker-helloworld .

    - name: Push Docker Image to Container Registry
      run: |
        echo "${{ secrets.dckr_pat_r8sAklusVZNFFeER0zCLSiYkbOo }}" | docker login -u ${{ secrets.ngv2003 }} --password-stdin
        docker push ngv03/docker-helloworld
